### ISSUE TITLE
Couldn't run your pretrained model using Scripts

### ISSUE THREAD

**Issue by HanhaodiZhang** [liuhaumin/LeadsheetArrangement#6]
--------------Start arrangement generation !!--------------
*running sampler...
Traceback (most recent call last):
  File "scripts.py", line 4, in <module>
    import main
  File "/home/ohla-ai/Projects/LeadsheetArrangement/main.py", line 62, in <module>
    musegan.gen_test(input_data, is_eval=True)
  File "/home/ohla-ai/Projects/LeadsheetArrangement/model/core.py", line 447, in gen_test
    type_=type_)
  File "/home/ohla-ai/Projects/LeadsheetArrangement/model/core.py", line 412, in run_sampler
    self.model.prediction_chroma], feed_dict=feed_dict)
  File "/home/ohla-ai/anaconda3/envs/tf15/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 956, in run
    run_metadata_ptr)
  File "/home/ohla-ai/anaconda3/envs/tf15/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1156, in _run
    (np_val.shape, subfeed_t.name, str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (64, 48, 84, 2) for Tensor 'NowbarHybrid/x:0', which has shape '(?, 48, 84, 5)'

Above is what I am occured, my input is a 2 track 8 bar midi file with melody and chords. Need your help please...

**Comment by liuhaumin** [comment]
Hello,
It looks like there is an unmatching of the dimension.
Have you tried the default files in /mysong_mid_C/?

**Comment by dianxin556** [comment]
I also meet the same problem with the default input files in /mysong_mid_C/

**Comment by CliffNewsted** [comment]
I also meet the same problem with the default input files in /mysong_mid_C/

**Comment by wangzi815** [comment]
I also meet the same problem with the default input files in /mysong_mid_C/.what is the problem?@liuhaumin，how to solve it?
